// Autogenerated with StateSmith 0.17.2+a7141c241054b3177bab267557ecb45a8dcedd67.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "lightbulb.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(lightbulb* sm, lightbulb_StateId desired_state);

static void ROOT_enter(lightbulb* sm);

static void OFF_enter(lightbulb* sm);

static void OFF_exit(lightbulb* sm);

static void OFF_switch(lightbulb* sm);

static void ON_enter(lightbulb* sm);

static void ON_exit(lightbulb* sm);

static void ON_switch(lightbulb* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void lightbulb_ctor(lightbulb* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void lightbulb_start(lightbulb* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(Off)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `Off`.
            OFF_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void lightbulb_dispatch_event(lightbulb* sm, lightbulb_EventId event_id)
{
    // This state machine design only has a single event type so we can safely assume
    // that the dispatched event is `switch` without checking the `event_id` parameter.
    (void)event_id; // This line prevents an 'unused variable' compiler warning
    
    switch (sm->state_id)
    {
        // STATE: lightbulb
        case lightbulb_StateId_ROOT:
            // state and ancestors have no handler for `switch` event.
            break;
        
        // STATE: Off
        case lightbulb_StateId_OFF:
            OFF_switch(sm); 
            break;
        
        // STATE: On
        case lightbulb_StateId_ON:
            ON_switch(sm); 
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(lightbulb* sm, lightbulb_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case lightbulb_StateId_OFF: OFF_exit(sm); break;
            
            case lightbulb_StateId_ON: ON_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(lightbulb* sm)
{
    sm->state_id = lightbulb_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state OFF
////////////////////////////////////////////////////////////////////////////////

static void OFF_enter(lightbulb* sm)
{
    sm->state_id = lightbulb_StateId_OFF;
    
    // Off behavior
    // uml: enter / { enter_off(); }
    {
        // Step 1: execute action `enter_off();`
        enter_off();
    } // end of behavior for Off
}

static void OFF_exit(lightbulb* sm)
{
    sm->state_id = lightbulb_StateId_ROOT;
}

static void OFF_switch(lightbulb* sm)
{
    // Off behavior
    // uml: Switch TransitionTo(On)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        OFF_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `On`.
        ON_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for Off
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON
////////////////////////////////////////////////////////////////////////////////

static void ON_enter(lightbulb* sm)
{
    sm->state_id = lightbulb_StateId_ON;
    
    // On behavior
    // uml: enter / { enter_on(); }
    {
        // Step 1: execute action `enter_on();`
        enter_on();
    } // end of behavior for On
}

static void ON_exit(lightbulb* sm)
{
    sm->state_id = lightbulb_StateId_ROOT;
}

static void ON_switch(lightbulb* sm)
{
    // On behavior
    // uml: Switch TransitionTo(Off)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ON_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `Off`.
        OFF_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for On
    
    // No ancestor handles this event.
}

// Thread safe.
char const * lightbulb_state_id_to_string(lightbulb_StateId id)
{
    switch (id)
    {
        case lightbulb_StateId_ROOT: return "ROOT";
        case lightbulb_StateId_OFF: return "OFF";
        case lightbulb_StateId_ON: return "ON";
        default: return "?";
    }
}

// Thread safe.
char const * lightbulb_event_id_to_string(lightbulb_EventId id)
{
    switch (id)
    {
        case lightbulb_EventId_SWITCH: return "SWITCH";
        default: return "?";
    }
}
