// Autogenerated with StateSmith
#include "Tutorial1Sm.h"
// Some user .c file comment...
#include "light.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

static void ROOT_enter(Tutorial1Sm* self);
static void ROOT_exit(Tutorial1Sm* self);

static void OFF_enter(Tutorial1Sm* self);
static void OFF_exit(Tutorial1Sm* self);
static void OFF_increase(Tutorial1Sm* self);

static void ON1_enter(Tutorial1Sm* self);
static void ON1_exit(Tutorial1Sm* self);
static void ON1_dim(Tutorial1Sm* self);
static void ON1_off(Tutorial1Sm* self);

static void exit_up_to_state_handler(Tutorial1Sm* self, const Tutorial1Sm_Func desired_state_exit_handler);


void Tutorial1Sm_ctor(Tutorial1Sm* self)
{
    memset(self, 0, sizeof(*self));
}

static void exit_up_to_state_handler(Tutorial1Sm* self, const Tutorial1Sm_Func desired_state_exit_handler)
{
    while (self->current_state_exit_handler != desired_state_exit_handler)
    {
        self->current_state_exit_handler(self);
    }
}

void Tutorial1Sm_start(Tutorial1Sm* self)
{
    ROOT_enter(self);
    // ROOT behavior
    // uml: TransitionTo(ROOT.InitialState)
    if (true)
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // At this point, StateSmith doesn't know what the active leaf state is. It could be ROOT or one of its sub states.
        exit_up_to_state_handler(self, ROOT_exit);  // Exit until we reach ROOT state.
        
        // Enter towards target
        
        // ROOT.InitialState behavior
        // uml: TransitionTo(OFF)
        if (true)
        {
            
            // Enter towards target
            OFF_enter(self);
            
            // update state_id
            self->state_id = Tutorial1Sm_StateId_OFF;
            self->ancestor_event_handler = NULL;
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for ROOT.InitialState
    } // end of behavior for ROOT
}

void Tutorial1Sm_dispatch_event(Tutorial1Sm* self, enum Tutorial1Sm_EventId event_id)
{
    Tutorial1Sm_Func behavior_func = self->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        self->ancestor_event_handler = NULL;
        behavior_func(self);
        behavior_func = self->ancestor_event_handler;
    }
}

const char* Tutorial1Sm_state_id_to_string(const enum Tutorial1Sm_StateId id)
{
    switch (id)
    {
        case Tutorial1Sm_StateId_ROOT: return "ROOT";
        case Tutorial1Sm_StateId_OFF: return "OFF";
        case Tutorial1Sm_StateId_ON1: return "ON1";
        default: return "?";
    }
}

////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Tutorial1Sm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = ROOT_exit;
}

static void ROOT_exit(Tutorial1Sm* self)
{
    // State machine root is a special case. It cannot be exited.
    (void)self;  // nothing to see here compiler. move along!
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state OFF
////////////////////////////////////////////////////////////////////////////////

static void OFF_enter(Tutorial1Sm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = OFF_exit;
    self->current_event_handlers[Tutorial1Sm_EventId_INCREASE] = OFF_increase;
    
    // OFF behavior
    // uml: enter / { light_off(); }
    if (true)
    {
        light_off();
    } // end of behavior for OFF
}

static void OFF_exit(Tutorial1Sm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[Tutorial1Sm_EventId_INCREASE] = NULL;  // no ancestor listens to this event
}

static void OFF_increase(Tutorial1Sm* self)
{
    // No ancestor state handles `INCREASE` event.
    
    // OFF behavior
    // uml: INCREASE TransitionTo(ON1)
    if (true)
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // Avoid exit-while-loop here because we know that the active leaf state is OFF and it is the only state being exited at this point.
        OFF_exit(self);
        
        // Enter towards target
        ON1_enter(self);
        
        // update state_id
        self->state_id = Tutorial1Sm_StateId_ON1;
        self->ancestor_event_handler = NULL;
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for OFF
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ON1
////////////////////////////////////////////////////////////////////////////////

static void ON1_enter(Tutorial1Sm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = ON1_exit;
    self->current_event_handlers[Tutorial1Sm_EventId_DIM] = ON1_dim;
    self->current_event_handlers[Tutorial1Sm_EventId_OFF] = ON1_off;
    
    // ON1 behavior
    // uml: enter / { light_on1(); }
    if (true)
    {
        light_on1();
    } // end of behavior for ON1
}

static void ON1_exit(Tutorial1Sm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
    self->current_event_handlers[Tutorial1Sm_EventId_DIM] = NULL;  // no ancestor listens to this event
    self->current_event_handlers[Tutorial1Sm_EventId_OFF] = NULL;  // no ancestor listens to this event
}

static void ON1_dim(Tutorial1Sm* self)
{
    // No ancestor state handles `DIM` event.
    
    // ON1 behavior
    // uml: DIM TransitionTo(OFF)
    if (true)
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // Avoid exit-while-loop here because we know that the active leaf state is ON1 and it is the only state being exited at this point.
        ON1_exit(self);
        
        // Enter towards target
        OFF_enter(self);
        
        // update state_id
        self->state_id = Tutorial1Sm_StateId_OFF;
        self->ancestor_event_handler = NULL;
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for ON1
}

static void ON1_off(Tutorial1Sm* self)
{
    // No ancestor state handles `OFF` event.
    
    // ON1 behavior
    // uml: OFF TransitionTo(OFF)
    if (true)
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // Avoid exit-while-loop here because we know that the active leaf state is ON1 and it is the only state being exited at this point.
        ON1_exit(self);
        
        // Enter towards target
        OFF_enter(self);
        
        // update state_id
        self->state_id = Tutorial1Sm_StateId_OFF;
        self->ancestor_event_handler = NULL;
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for ON1
}


