// Autogenerated with StateSmith 0.9.4-alpha-fix-1.
// Algorithm: Balanced1. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once
#include <stdint.h>

// any text you put in IRenderConfigC.HFileIncludes (like this comment) will be written to the generated .h file
typedef enum LaserTagMenu1Sm_EventId
{
    LaserTagMenu1Sm_EventId_DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
    LaserTagMenu1Sm_EventId_BACK_HELD = 1,
    LaserTagMenu1Sm_EventId_BACK_PRESS = 2,
    LaserTagMenu1Sm_EventId_DOWN_HELD = 3,
    LaserTagMenu1Sm_EventId_DOWN_PRESS = 4,
    LaserTagMenu1Sm_EventId_OK_PRESS = 5,
    LaserTagMenu1Sm_EventId_UP_HELD = 6,
    LaserTagMenu1Sm_EventId_UP_PRESS = 7,
} LaserTagMenu1Sm_EventId;

enum
{
    LaserTagMenu1Sm_EventIdCount = 8
};

typedef enum LaserTagMenu1Sm_StateId
{
    LaserTagMenu1Sm_StateId_ROOT = 0,
    LaserTagMenu1Sm_StateId_HOME = 1,
    LaserTagMenu1Sm_StateId_HOME1 = 2,
    LaserTagMenu1Sm_StateId_HOME2 = 3,
    LaserTagMenu1Sm_StateId_HOME3 = 4,
    LaserTagMenu1Sm_StateId_MENUS_GROUP = 5,
    LaserTagMenu1Sm_StateId_CLASS_SAVED = 6,
    LaserTagMenu1Sm_StateId_MAIN_MENU = 7,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_OPTION = 8,
    LaserTagMenu1Sm_StateId_MM_SELECT_CLASS_OPTION = 9,
    LaserTagMenu1Sm_StateId_MM_SHOW_INFO_OPTION = 10,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER = 11,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_1 = 12,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_2 = 13,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_3 = 14,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_4 = 15,
    LaserTagMenu1Sm_StateId_MM_BACK_PRESS_EATER_5 = 16,
    LaserTagMenu1Sm_StateId_MM_SELECT_CLASS = 17,
    LaserTagMenu1Sm_StateId_MM_SC_ENGINEER = 18,
    LaserTagMenu1Sm_StateId_MM_SC_MID = 19,
    LaserTagMenu1Sm_StateId_MM_SC_ARCHER = 20,
    LaserTagMenu1Sm_StateId_MM_SC_HEAVY = 21,
    LaserTagMenu1Sm_StateId_MM_SC_WIZARD = 22,
    LaserTagMenu1Sm_StateId_MM_SC_SPY = 23,
    LaserTagMenu1Sm_StateId_MM_SHOW_INFO = 24,
    LaserTagMenu1Sm_StateId_MM_SHOW_INFO_1 = 25,
    LaserTagMenu1Sm_StateId_MM_SHOW_INFO_2 = 26,
    LaserTagMenu1Sm_StateId_MM_SHOW_INFO_3 = 27,
    LaserTagMenu1Sm_StateId_WELCOME_SCREEN = 28,
} LaserTagMenu1Sm_StateId;

enum
{
    LaserTagMenu1Sm_StateIdCount = 29
};


// Generated state machine
// forward declaration
typedef struct LaserTagMenu1Sm LaserTagMenu1Sm;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct LaserTagMenu1Sm_Vars
{
    uint8_t option_value;
    uint8_t back_press_eat_count;
    uint32_t timer1_started_at_ms;
} LaserTagMenu1Sm_Vars;


// event handler type
typedef void (*LaserTagMenu1Sm_Func)(LaserTagMenu1Sm* sm);

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void LaserTagMenu1Sm_ctor(LaserTagMenu1Sm* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void LaserTagMenu1Sm_start(LaserTagMenu1Sm* sm);

// Dispatches an event to the state machine. Not thread safe.
void LaserTagMenu1Sm_dispatch_event(LaserTagMenu1Sm* sm, LaserTagMenu1Sm_EventId event_id);

// Thread safe.
char const * LaserTagMenu1Sm_state_id_to_string(LaserTagMenu1Sm_StateId id);

// Thread safe.
char const * LaserTagMenu1Sm_event_id_to_string(LaserTagMenu1Sm_EventId id);

// Generated state machine
struct LaserTagMenu1Sm
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    LaserTagMenu1Sm_StateId state_id;
    
    // Used internally by state machine. Don't modify.
    LaserTagMenu1Sm_Func ancestor_event_handler;
    
    // Used internally by state machine. Don't modify.
    LaserTagMenu1Sm_Func current_event_handlers[LaserTagMenu1Sm_EventIdCount];
    
    // Used internally by state machine. Don't modify.
    LaserTagMenu1Sm_Func current_state_exit_handler;
    
    // Variables. Can be used for inputs, outputs, user variables...
    LaserTagMenu1Sm_Vars vars;
};

