//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar1.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class Grammar1Lexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, LINE_ENDER=16, 
		IDENTIFIER=17, LINE_COMMENT=18, STAR_COMMENT=19, STRING=20, TICK_STRING=21, 
		DIGIT=22, PERIOD=23, COMMA=24, PLUS=25, DASH=26, COLON=27, GT=28, LT=29, 
		OTHER_SYMBOLS=30, HWS=31;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "LINE_ENDER", "IDENTIFIER", 
		"NOT_NL_CR", "LINE_COMMENT", "STAR_COMMENT", "ESCAPED_CHAR", "NON_QUOTE_CHAR", 
		"STRING_CHAR", "STRING", "TICK_STRING", "IDENTIFIER_NON_DIGIT", "DIGIT", 
		"PERIOD", "COMMA", "PLUS", "DASH", "COLON", "GT", "LT", "OTHER_SYMBOLS", 
		"HWS"
	};


	public Grammar1Lexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Grammar1Lexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'$STATEMACHINE'", "'$NOTES'", "'$ORTHO'", "'#'", "'$entry_'", "'exit'", 
		"'via'", "'('", "')'", "'['", "']'", "'/'", "'{'", "'}'", "'e'", null, 
		null, null, null, null, null, null, "'.'", "','", "'+'", "'-'", "':'", 
		"'>'", "'<'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, "LINE_ENDER", "IDENTIFIER", "LINE_COMMENT", "STAR_COMMENT", 
		"STRING", "TICK_STRING", "DIGIT", "PERIOD", "COMMA", "PLUS", "DASH", "COLON", 
		"GT", "LT", "OTHER_SYMBOLS", "HWS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Grammar1.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Grammar1Lexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '!', '\xE2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x6', '\x11', '\x8C', '\n', '\x11', '\r', '\x11', '\xE', 
		'\x11', '\x8D', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\a', '\x12', 
		'\x93', '\n', '\x12', '\f', '\x12', '\xE', '\x12', '\x96', '\v', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\a', '\x14', '\x9E', '\n', '\x14', '\f', '\x14', '\xE', 
		'\x14', '\xA1', '\v', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\a', '\x15', '\xA7', '\n', '\x15', '\f', '\x15', '\xE', 
		'\x15', '\xAA', '\v', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\xB6', '\n', '\x18', '\x3', 
		'\x19', '\x3', '\x19', '\a', '\x19', '\xBA', '\n', '\x19', '\f', '\x19', 
		'\xE', '\x19', '\xBD', '\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\a', '\x1A', '\xC3', '\n', '\x1A', '\f', '\x1A', 
		'\xE', '\x1A', '\xC6', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', 
		' ', '\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', 
		'#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', '%', '\x6', '%', '\xDF', 
		'\n', '%', '\r', '%', '\xE', '%', '\xE0', '\x3', '\xA8', '\x2', '&', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x2', '\'', '\x14', ')', '\x15', '+', '\x2', '-', '\x2', 
		'/', '\x2', '\x31', '\x16', '\x33', '\x17', '\x35', '\x2', '\x37', '\x18', 
		'\x39', '\x19', ';', '\x1A', '=', '\x1B', '?', '\x1C', '\x41', '\x1D', 
		'\x43', '\x1E', '\x45', '\x1F', 'G', ' ', 'I', '!', '\x3', '\x2', '\t', 
		'\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', '\x2', '$', '$', '\x3', 
		'\x2', ')', ')', '\x6', '\x2', '&', '&', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x3', '\x2', '\x32', ';', '\f', '\x2', '#', '#', '\'', '(', 
		',', ',', '\x31', '\x31', '<', '=', '?', '?', '\x41', '\x41', '`', '`', 
		'~', '~', '\x80', '\x80', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', 
		'\xE5', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'I', '\x3', '\x2', '\x2', '\x2', '\x3', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\x5', 'Y', '\x3', '\x2', '\x2', '\x2', '\a', '`', 
		'\x3', '\x2', '\x2', '\x2', '\t', 'g', '\x3', '\x2', '\x2', '\x2', '\v', 
		'i', '\x3', '\x2', '\x2', '\x2', '\r', 'q', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'v', '\x3', '\x2', '\x2', '\x2', '\x11', 'z', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '|', '\x3', '\x2', '\x2', '\x2', '\x15', '~', '\x3', '\x2', 
		'\x2', '\x2', '\x17', '\x80', '\x3', '\x2', '\x2', '\x2', '\x19', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', '\x84', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '\x86', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x88', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x8B', '\x3', '\x2', '\x2', '\x2', '#', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '%', '\x97', '\x3', '\x2', '\x2', '\x2', '\'', '\x99', 
		'\x3', '\x2', '\x2', '\x2', ')', '\xA2', '\x3', '\x2', '\x2', '\x2', '+', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '-', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '/', '\xB5', '\x3', '\x2', '\x2', '\x2', '\x31', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\xC0', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\xC9', '\x3', '\x2', '\x2', '\x2', '\x37', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\xCD', '\x3', '\x2', '\x2', '\x2', ';', '\xCF', '\x3', 
		'\x2', '\x2', '\x2', '=', '\xD1', '\x3', '\x2', '\x2', '\x2', '?', '\xD3', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\xD5', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\xD7', '\x3', '\x2', '\x2', '\x2', '\x45', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', 'G', '\xDB', '\x3', '\x2', '\x2', '\x2', 'I', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', 'K', 'L', '\a', '&', '\x2', '\x2', 'L', 'M', '\a', 
		'U', '\x2', '\x2', 'M', 'N', '\a', 'V', '\x2', '\x2', 'N', 'O', '\a', 
		'\x43', '\x2', '\x2', 'O', 'P', '\a', 'V', '\x2', '\x2', 'P', 'Q', '\a', 
		'G', '\x2', '\x2', 'Q', 'R', '\a', 'O', '\x2', '\x2', 'R', 'S', '\a', 
		'\x43', '\x2', '\x2', 'S', 'T', '\a', '\x45', '\x2', '\x2', 'T', 'U', 
		'\a', 'J', '\x2', '\x2', 'U', 'V', '\a', 'K', '\x2', '\x2', 'V', 'W', 
		'\a', 'P', '\x2', '\x2', 'W', 'X', '\a', 'G', '\x2', '\x2', 'X', '\x4', 
		'\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '&', '\x2', '\x2', 'Z', '[', 
		'\a', 'P', '\x2', '\x2', '[', '\\', '\a', 'Q', '\x2', '\x2', '\\', ']', 
		'\a', 'V', '\x2', '\x2', ']', '^', '\a', 'G', '\x2', '\x2', '^', '_', 
		'\a', 'U', '\x2', '\x2', '_', '\x6', '\x3', '\x2', '\x2', '\x2', '`', 
		'\x61', '\a', '&', '\x2', '\x2', '\x61', '\x62', '\a', 'Q', '\x2', '\x2', 
		'\x62', '\x63', '\a', 'T', '\x2', '\x2', '\x63', '\x64', '\a', 'V', '\x2', 
		'\x2', '\x64', '\x65', '\a', 'J', '\x2', '\x2', '\x65', '\x66', '\a', 
		'Q', '\x2', '\x2', '\x66', '\b', '\x3', '\x2', '\x2', '\x2', 'g', 'h', 
		'\a', '%', '\x2', '\x2', 'h', '\n', '\x3', '\x2', '\x2', '\x2', 'i', 'j', 
		'\a', '&', '\x2', '\x2', 'j', 'k', '\a', 'g', '\x2', '\x2', 'k', 'l', 
		'\a', 'p', '\x2', '\x2', 'l', 'm', '\a', 'v', '\x2', '\x2', 'm', 'n', 
		'\a', 't', '\x2', '\x2', 'n', 'o', '\a', '{', '\x2', '\x2', 'o', 'p', 
		'\a', '\x61', '\x2', '\x2', 'p', '\f', '\x3', '\x2', '\x2', '\x2', 'q', 
		'r', '\a', 'g', '\x2', '\x2', 'r', 's', '\a', 'z', '\x2', '\x2', 's', 
		't', '\a', 'k', '\x2', '\x2', 't', 'u', '\a', 'v', '\x2', '\x2', 'u', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', 'x', '\x2', '\x2', 
		'w', 'x', '\a', 'k', '\x2', '\x2', 'x', 'y', '\a', '\x63', '\x2', '\x2', 
		'y', '\x10', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '*', '\x2', '\x2', 
		'{', '\x12', '\x3', '\x2', '\x2', '\x2', '|', '}', '\a', '+', '\x2', '\x2', 
		'}', '\x14', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', ']', '\x2', 
		'\x2', '\x7F', '\x16', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', 
		'_', '\x2', '\x2', '\x81', '\x18', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x83', '\a', '\x31', '\x2', '\x2', '\x83', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x85', '\a', '}', '\x2', '\x2', '\x85', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x87', '\a', '\x7F', '\x2', '\x2', '\x87', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\a', 'g', '\x2', 
		'\x2', '\x89', ' ', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\t', 
		'\x2', '\x2', '\x2', '\x8B', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x94', '\x5', '\x35', '\x1B', '\x2', '\x90', 
		'\x93', '\x5', '\x35', '\x1B', '\x2', '\x91', '\x93', '\x5', '\x37', '\x1C', 
		'\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x96', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '$', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\n', '\x2', '\x2', '\x2', '\x98', 
		'&', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x31', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', '\x31', '\x2', '\x2', '\x9B', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\x5', '%', '\x13', '\x2', '\x9D', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '(', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '\x31', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', ',', '\x2', '\x2', '\xA4', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '\xA7', '\v', '\x2', '\x2', '\x2', '\xA6', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', ',', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', '\x31', '\x2', '\x2', '\xAD', '*', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', '^', '\x2', '\x2', '\xAF', 
		'\xB0', '\v', '\x2', '\x2', '\x2', '\xB0', ',', '\x3', '\x2', '\x2', '\x2', 
		'\xB1', '\xB2', '\n', '\x3', '\x2', '\x2', '\xB2', '.', '\x3', '\x2', 
		'\x2', '\x2', '\xB3', '\xB6', '\x5', '+', '\x16', '\x2', '\xB4', '\xB6', 
		'\x5', '-', '\x17', '\x2', '\xB5', '\xB3', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\xB7', '\xBB', '\a', '$', '\x2', '\x2', '\xB8', '\xBA', 
		'\x5', '/', '\x18', '\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', 
		'\xBA', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', 
		'\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', '\x2', 
		'\xBE', '\xBF', '\a', '$', '\x2', '\x2', '\xBF', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\xC0', '\xC4', '\t', '\x4', '\x2', '\x2', '\xC1', '\xC3', 
		'\x5', '/', '\x18', '\x2', '\xC2', '\xC1', '\x3', '\x2', '\x2', '\x2', 
		'\xC3', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC7', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC8', '\t', '\x4', '\x2', '\x2', '\xC8', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCA', '\t', '\x5', '\x2', '\x2', '\xCA', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xCB', '\xCC', '\t', '\x6', '\x2', '\x2', 
		'\xCC', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\a', '\x30', 
		'\x2', '\x2', '\xCE', ':', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', 
		'\a', '.', '\x2', '\x2', '\xD0', '<', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD2', '\a', '-', '\x2', '\x2', '\xD2', '>', '\x3', '\x2', '\x2', '\x2', 
		'\xD3', '\xD4', '\a', '/', '\x2', '\x2', '\xD4', '@', '\x3', '\x2', '\x2', 
		'\x2', '\xD5', '\xD6', '\a', '<', '\x2', '\x2', '\xD6', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '\xD7', '\xD8', '\a', '@', '\x2', '\x2', '\xD8', 
		'\x44', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\a', '>', '\x2', 
		'\x2', '\xDA', '\x46', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\t', 
		'\a', '\x2', '\x2', '\xDC', 'H', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDF', 
		'\t', '\b', '\x2', '\x2', '\xDE', '\xDD', '\x3', '\x2', '\x2', '\x2', 
		'\xDF', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', '\xE0', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xE1', 'J', 
		'\x3', '\x2', '\x2', '\x2', '\f', '\x2', '\x8D', '\x92', '\x94', '\x9F', 
		'\xA8', '\xB5', '\xBB', '\xC4', '\xE0', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
