//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlantumlGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class PlantumlGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		START_UML=10, END_UML=11, HWS=12, LINE_ENDER=13, IDENTIFIER=14, DIGIT=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"IDENTIFIER_NON_DIGIT", "START_UML", "END_UML", "HWS", "LINE_ENDER", "IDENTIFIER", 
		"DIGIT"
	};


	public PlantumlGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlantumlGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'[*]'", "'->'", "'-->'", "':'", "'state'", "'{'", "'}'", "'hide empty description'", 
		"'scale '", "'@startuml'", "'@enduml'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "START_UML", 
		"END_UML", "HWS", "LINE_ENDER", "IDENTIFIER", "DIGIT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlantumlGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PlantumlGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x11', '\x80', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x6', '\xE', 'n', '\n', '\xE', '\r', '\xE', '\xE', '\xE', 'o', 
		'\x3', '\xF', '\x6', '\xF', 's', '\n', '\xF', '\r', '\xF', '\xE', '\xF', 
		't', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', 'z', '\n', 
		'\x10', '\f', '\x10', '\xE', '\x10', '}', '\v', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x2', '\x2', '\x12', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\x2', '\x17', '\f', '\x19', '\r', '\x1B', '\xE', 
		'\x1D', '\xF', '\x1F', '\x10', '!', '\x11', '\x3', '\x2', '\x6', '\x5', 
		'\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x4', '\x2', '\v', 
		'\v', '\"', '\"', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x3', '\x2', 
		'\x32', ';', '\x2', '\x82', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x3', '#', '\x3', '\x2', '\x2', '\x2', '\x5', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\a', '*', '\x3', '\x2', '\x2', '\x2', '\t', '.', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x30', '\x3', '\x2', '\x2', '\x2', '\r', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\x11', ':', '\x3', '\x2', '\x2', '\x2', '\x13', 'Q', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'X', '\x3', '\x2', '\x2', '\x2', '\x17', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\x19', '\x64', '\x3', '\x2', '\x2', '\x2', '\x1B', 'm', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', 'r', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'v', '\x3', '\x2', '\x2', '\x2', '!', '~', '\x3', '\x2', '\x2', '\x2', 
		'#', '$', '\a', ']', '\x2', '\x2', '$', '%', '\a', ',', '\x2', '\x2', 
		'%', '&', '\a', '_', '\x2', '\x2', '&', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\'', '(', '\a', '/', '\x2', '\x2', '(', ')', '\a', '@', '\x2', '\x2', 
		')', '\x6', '\x3', '\x2', '\x2', '\x2', '*', '+', '\a', '/', '\x2', '\x2', 
		'+', ',', '\a', '/', '\x2', '\x2', ',', '-', '\a', '@', '\x2', '\x2', 
		'-', '\b', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', '<', '\x2', '\x2', 
		'/', '\n', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', 'u', '\x2', 
		'\x2', '\x31', '\x32', '\a', 'v', '\x2', '\x2', '\x32', '\x33', '\a', 
		'\x63', '\x2', '\x2', '\x33', '\x34', '\a', 'v', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'g', '\x2', '\x2', '\x35', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x36', '\x37', '\a', '}', '\x2', '\x2', '\x37', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '\x39', '\a', '\x7F', '\x2', '\x2', '\x39', '\x10', 
		'\x3', '\x2', '\x2', '\x2', ':', ';', '\a', 'j', '\x2', '\x2', ';', '<', 
		'\a', 'k', '\x2', '\x2', '<', '=', '\a', '\x66', '\x2', '\x2', '=', '>', 
		'\a', 'g', '\x2', '\x2', '>', '?', '\a', '\"', '\x2', '\x2', '?', '@', 
		'\a', 'g', '\x2', '\x2', '@', '\x41', '\a', 'o', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'r', '\x2', '\x2', '\x42', '\x43', '\a', 'v', '\x2', '\x2', 
		'\x43', '\x44', '\a', '{', '\x2', '\x2', '\x44', '\x45', '\a', '\"', '\x2', 
		'\x2', '\x45', '\x46', '\a', '\x66', '\x2', '\x2', '\x46', 'G', '\a', 
		'g', '\x2', '\x2', 'G', 'H', '\a', 'u', '\x2', '\x2', 'H', 'I', '\a', 
		'\x65', '\x2', '\x2', 'I', 'J', '\a', 't', '\x2', '\x2', 'J', 'K', '\a', 
		'k', '\x2', '\x2', 'K', 'L', '\a', 'r', '\x2', '\x2', 'L', 'M', '\a', 
		'v', '\x2', '\x2', 'M', 'N', '\a', 'k', '\x2', '\x2', 'N', 'O', '\a', 
		'q', '\x2', '\x2', 'O', 'P', '\a', 'p', '\x2', '\x2', 'P', '\x12', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', 'u', '\x2', '\x2', 'R', 'S', '\a', 
		'\x65', '\x2', '\x2', 'S', 'T', '\a', '\x63', '\x2', '\x2', 'T', 'U', 
		'\a', 'n', '\x2', '\x2', 'U', 'V', '\a', 'g', '\x2', '\x2', 'V', 'W', 
		'\a', '\"', '\x2', '\x2', 'W', '\x14', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\t', '\x2', '\x2', '\x2', 'Y', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'Z', '[', '\a', '\x42', '\x2', '\x2', '[', '\\', '\a', 'u', '\x2', '\x2', 
		'\\', ']', '\a', 'v', '\x2', '\x2', ']', '^', '\a', '\x63', '\x2', '\x2', 
		'^', '_', '\a', 't', '\x2', '\x2', '_', '`', '\a', 'v', '\x2', '\x2', 
		'`', '\x61', '\a', 'w', '\x2', '\x2', '\x61', '\x62', '\a', 'o', '\x2', 
		'\x2', '\x62', '\x63', '\a', 'n', '\x2', '\x2', '\x63', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\a', '\x42', '\x2', '\x2', '\x65', 
		'\x66', '\a', 'g', '\x2', '\x2', '\x66', 'g', '\a', 'p', '\x2', '\x2', 
		'g', 'h', '\a', '\x66', '\x2', '\x2', 'h', 'i', '\a', 'w', '\x2', '\x2', 
		'i', 'j', '\a', 'o', '\x2', '\x2', 'j', 'k', '\a', 'n', '\x2', '\x2', 
		'k', '\x1A', '\x3', '\x2', '\x2', '\x2', 'l', 'n', '\t', '\x3', '\x2', 
		'\x2', 'm', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', '\x2', 
		'\x2', 'p', '\x1C', '\x3', '\x2', '\x2', '\x2', 'q', 's', '\t', '\x4', 
		'\x2', '\x2', 'r', 'q', '\x3', '\x2', '\x2', '\x2', 's', 't', '\x3', '\x2', 
		'\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', 
		'\x2', '\x2', 'u', '\x1E', '\x3', '\x2', '\x2', '\x2', 'v', '{', '\x5', 
		'\x15', '\v', '\x2', 'w', 'z', '\x5', '\x15', '\v', '\x2', 'x', 'z', '\x5', 
		'!', '\x11', '\x2', 'y', 'w', '\x3', '\x2', '\x2', '\x2', 'y', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'z', '}', '\x3', '\x2', '\x2', '\x2', '{', 'y', '\x3', 
		'\x2', '\x2', '\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', '|', ' ', '\x3', 
		'\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', 
		'\t', '\x5', '\x2', '\x2', '\x7F', '\"', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x2', 'o', 't', 'y', '{', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
