// Autogenerated with StateSmith
#include "Spec1bSm.h"
#include "../../lang-helpers/c/helper.h"
#include "printer.h"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

static void ROOT_enter(Spec1bSm* self);
static void ROOT_exit(Spec1bSm* self);

static void S_enter(Spec1bSm* self);
static void S_exit(Spec1bSm* self);

static void S1_enter(Spec1bSm* self);
static void S1_exit(Spec1bSm* self);
static void S1_t1(Spec1bSm* self);

static void S1_1_enter(Spec1bSm* self);
static void S1_1_exit(Spec1bSm* self);

static void S2_enter(Spec1bSm* self);
static void S2_exit(Spec1bSm* self);

static void S2_1_enter(Spec1bSm* self);
static void S2_1_exit(Spec1bSm* self);

static void exit_up_to_state_handler(Spec1bSm* self, const Spec1bSm_Func desired_state_exit_handler);


void Spec1bSm_ctor(Spec1bSm* self)
{
    memset(self, 0, sizeof(*self));
}

static void exit_up_to_state_handler(Spec1bSm* self, const Spec1bSm_Func desired_state_exit_handler)
{
    while (self->current_state_exit_handler != desired_state_exit_handler)
    {
        self->current_state_exit_handler(self);
    }
}

void Spec1bSm_start(Spec1bSm* self)
{
    ROOT_enter(self);
    // ROOT behavior
    // uml: TransitionTo(ROOT.InitialState)
    if (true)
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // At this point, StateSmith doesn't know what the active leaf state is. It could be ROOT or one of its sub states.
        exit_up_to_state_handler(self, ROOT_exit);  // Exit until we reach ROOT state.
        
        // Enter towards target
        
        // ROOT.InitialState behavior
        // uml: TransitionTo(S)
        if (true)
        {
            
            // Enter towards target
            S_enter(self);
            
            // S.InitialState behavior
            // uml: TransitionTo(S1)
            if (true)
            {
                
                // Enter towards target
                S1_enter(self);
                
                // S1.InitialState behavior
                // uml: TransitionTo(S1_1)
                if (true)
                {
                    
                    // Enter towards target
                    S1_1_enter(self);
                    
                    // update state_id
                    self->state_id = Spec1bSm_StateId_S1_1;
                    self->ancestor_event_handler = NULL;
                    return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
                } // end of behavior for S1.InitialState
            } // end of behavior for S.InitialState
        } // end of behavior for ROOT.InitialState
    } // end of behavior for ROOT
}

void Spec1bSm_dispatch_event(Spec1bSm* self, enum Spec1bSm_EventId event_id)
{
    Spec1bSm_Func behavior_func = self->current_event_handlers[event_id];
    
    while (behavior_func != NULL)
    {
        self->ancestor_event_handler = NULL;
        behavior_func(self);
        behavior_func = self->ancestor_event_handler;
    }
}

const char* Spec1bSm_state_id_to_string(const enum Spec1bSm_StateId id)
{
    switch (id)
    {
        case Spec1bSm_StateId_ROOT: return "ROOT";
        case Spec1bSm_StateId_S: return "S";
        case Spec1bSm_StateId_S1: return "S1";
        case Spec1bSm_StateId_S1_1: return "S1_1";
        case Spec1bSm_StateId_S2: return "S2";
        case Spec1bSm_StateId_S2_1: return "S2_1";
        default: return "?";
    }
}

////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = ROOT_exit;
}

static void ROOT_exit(Spec1bSm* self)
{
    // State machine root is a special case. It cannot be exited.
    (void)self;  // nothing to see here compiler. move along!
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state S
////////////////////////////////////////////////////////////////////////////////

static void S_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = S_exit;
}

static void S_exit(Spec1bSm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = ROOT_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state S1
////////////////////////////////////////////////////////////////////////////////

static void S1_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = S1_exit;
    self->current_event_handlers[Spec1bSm_EventId_T1] = S1_t1;
}

static void S1_exit(Spec1bSm* self)
{
    // S1 behavior
    // uml: exit / { b(); }
    if (true)
    {
        print("b(); ");
    } // end of behavior for S1
    
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = S_exit;
    self->current_event_handlers[Spec1bSm_EventId_T1] = NULL;  // no ancestor listens to this event
}

static void S1_t1(Spec1bSm* self)
{
    // No ancestor state handles `T1` event.
    
    // S1 behavior
    // uml: T1 [g()] / { t(); } TransitionTo(S2)
    if (print("g() "))
    {
        // Note: no `consume_event` variable possible here because of state transition. The event must be consumed.
        // At this point, StateSmith doesn't know what the active leaf state is. It could be S1 or one of its sub states.
        exit_up_to_state_handler(self, S_exit);  // Exit until we reach S state.
        print("t(); ");
        
        // Enter towards target
        S2_enter(self);
        
        // S2.InitialState behavior
        // uml: / { d(); } TransitionTo(S2_1)
        if (true)
        {
            print("d(); ");
            
            // Enter towards target
            S2_1_enter(self);
            
            // update state_id
            self->state_id = Spec1bSm_StateId_S2_1;
            self->ancestor_event_handler = NULL;
            return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
        } // end of behavior for S2.InitialState
    } // end of behavior for S1
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state S1_1
////////////////////////////////////////////////////////////////////////////////

static void S1_1_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = S1_1_exit;
}

static void S1_1_exit(Spec1bSm* self)
{
    // S1_1 behavior
    // uml: exit / { a(); }
    if (true)
    {
        print("a(); ");
    } // end of behavior for S1_1
    
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = S1_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state S2
////////////////////////////////////////////////////////////////////////////////

static void S2_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = S2_exit;
    
    // S2 behavior
    // uml: enter / { c(); }
    if (true)
    {
        print("c(); ");
    } // end of behavior for S2
}

static void S2_exit(Spec1bSm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = S_exit;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state S2_1
////////////////////////////////////////////////////////////////////////////////

static void S2_1_enter(Spec1bSm* self)
{
    // setup trigger/event handlers
    self->current_state_exit_handler = S2_1_exit;
    
    // S2_1 behavior
    // uml: enter / { e(); }
    if (true)
    {
        print("e(); ");
    } // end of behavior for S2_1
}

static void S2_1_exit(Spec1bSm* self)
{
    // adjust function pointers for this state's exit
    self->current_state_exit_handler = S2_exit;
}


