@startuml lightbulb
[*] -> Off
Off -> On : Switch
On -> Off : Switch

' Use actions to call functions on various triggers, 
' such as entering or exiting a state.
' You can call these functions whatever you want.
' You will define these functions in your app.
Off: enter / enter_off();
On: enter / enter_on();
@enduml
