source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.10.1" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# https://github.com/just-the-docs/just-the-docs/issues/1607
gem 'jekyll-sass-converter', '~> 3.1.0'

gem "jekyll-plantuml", '~> 1.4.2'
