@startuml

frame output [
{{
  object "C / C++"
  object "C#"
  object "JavaScript\nTypeScript"
  object Python
}}
]

object "draw.io" as drawio
object plantuml
object yed
object statesmith

statesmith : <img:media/logo.png{scale=0.1}>


drawio --> statesmith
plantuml --> statesmith
yed --> statesmith

statesmith --> output

@enduml