name: Run makefiles in docs directory
on:
  push:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2

      # plantuml version on apt is ancient so we use homebrew
      # TODO this is ridiculously inefficient
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install dependencies
        run: brew install plantuml

      - name: Install ss.cli
        run: dotnet tool install --global StateSmith.Cli --version 0.17.5

      - name: Run makefiles
        run: find docs -name 'Makefile' -execdir make \;

      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Run makefiles in docs directory"
          branch: ${{ github.head_ref }}
