name: build

on:      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: |
                9.x

      - name: Add .NET tools to PATH
        run: echo '/root/.dotnet/tools' >> $GITHUB_PATH

      - name: Verify dotnet
        run: dotnet --version

      - name: create sample script
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/statesmith
          # TODO version
          dotnet publish -c Release --framework net9.0 --no-self-contained --use-current-runtime -p:Version=0.1.0 -o .debpkg/usr/lib/statesmith src/StateSmith.Cli
          echo -e "#!/bin/bash\n/usr/bin/dotnet /usr/lib/statesmith/StateSmith.Cli \"\$@\"" > .debpkg/usr/bin/statesmith
          chmod +x .debpkg/usr/bin/statesmith

      - uses: jiro4989/build-deb-action@v4
        with:
          package: statesmith
          package_root: .debpkg
          maintainer: Adam Fraser-Kruck
          version: 0.1.0 # TODO version
        #   version: ${{ github.ref }} # refs/tags/v*.*.*
        #   arch: 'amd64' # optional
          depends: 'dotnet-sdk-8.0 (>= 8.0), git'
          desc: 'A state machine code generation tool suitable for bare metal, embedded and more.'
          homepage: 'https://github.com/StateSmith'
        id: build

      # Check a created deb file
      - name: Check a path of deb file
        run: ls ${{ steps.build.outputs.file_name }}